# Binary Classification - Neural Network

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

## DataSet

In [7]:
path = "dataset-01/iris/"
dataSet = pd.read_csv(path+'iris.csv')
dataSet = dataSet[:100] # Only 2 classes: Iris-setosa and Iris-versicolor
#print(dataSet)
# Shuffling dataframe
data = dataSet.sample(frac=1).reset_index(drop=True)

data[20:40]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
20,76,6.6,3.0,4.4,1.4,Iris-versicolor
21,12,4.8,3.4,1.6,0.2,Iris-setosa
22,51,7.0,3.2,4.7,1.4,Iris-versicolor
23,68,5.8,2.7,4.1,1.0,Iris-versicolor
24,27,5.0,3.4,1.6,0.4,Iris-setosa
25,17,5.4,3.9,1.3,0.4,Iris-setosa
26,16,5.7,4.4,1.5,0.4,Iris-setosa
27,66,6.7,3.1,4.4,1.4,Iris-versicolor
28,50,5.0,3.3,1.4,0.2,Iris-setosa
29,77,6.8,2.8,4.8,1.4,Iris-versicolor
30,70,5.6,2.5,3.9,1.1,Iris-versicolor
31,81,5.5,2.4,3.8,1.1,Iris-versicolor
32,20,5.1,3.8,1.5,0.3,Iris-setosa
33,41,5.0,3.5,1.3,0.3,Iris-setosa
34,97,5.7,2.9,4.2,1.3,Iris-versicolor
35,30,4.7,3.2,1.6,0.2,Iris-setosa
36,33,5.2,4.1,1.5,0.1,Iris-setosa
37,9,4.4,2.9,1.4,0.2,Iris-setosa
38,69,6.2,2.2,4.5,1.5,Iris-versicolor
39,29,5.2,3.4,1.4,0.2,Iris-setosa

In [8]:
data["Species"] = data["Species"].apply(lambda x: x.replace("Iris-setosa", "0"))
data["Species"] = data["Species"].apply(lambda x: x.replace("Iris-versicolor", "1"))
data = data.astype(float)
data[:20]

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   52.0            6.4           3.2            4.5           1.5      1.0
1   79.0            6.0           2.9            4.5           1.5      1.0
2   42.0            4.5           2.3            1.3           0.3      0.0
3   80.0            5.7           2.6            3.5           1.0      1.0
4   91.0            5.5           2.6            4.4           1.2      1.0
5   32.0            5.4           3.4            1.5           0.4      0.0
6   74.0            6.1           2.8            4.7           1.2      1.0
7   56.0            5.7           2.8            4.5           1.3      1.0
8   37.0            5.5           3.5            1.3           0.2      0.0
9   48.0            4.6           3.2            1.4           0.2      0.0
10  78.0            6.7           3.0            5.0           1.7      1.0
11  38.0            4.9           3.1            1.5           0.1      0.0
12  62.0            5.9           3.0            4.2           1.5      1.0
13  89.0            5.6           3.0            4.1           1.3      1.0
14  95.0            5.6           2.7            4.2           1.3      1.0
15  98.0            6.2           2.9            4.3           1.3      1.0
16  40.0            5.1           3.4            1.5           0.2      0.0
17  22.0            5.1           3.7            1.5           0.4      0.0
18  90.0            5.5           2.5            4.0           1.3      1.0
19  28.0            5.2           3.5            1.5           0.2      0.0

In [9]:
X = data.iloc[ : , 1:5 ].values
y = data.iloc[ : , 5:6 ].values
y = y.astype(int)

In [10]:
print(X[:5])
print(y[:5])
print(np.shape(X))
print(np.shape(y))

[[6.4 3.2 4.5 1.5]
 [6.  2.9 4.5 1.5]
 [4.5 2.3 1.3 0.3]
 [5.7 2.6 3.5 1. ]
 [5.5 2.6 4.4 1.2]]
[[1]
 [1]
 [0]
 [1]
 [1]]
(100, 4)
(100, 1)

# Dataset split

In [11]:
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=10)

In [13]:
print(len(X_test))

20

## Tensorflow Model

### Model

In [14]:
model = Sequential([
    Dense(4, activation = 'relu', name = 'layer1'),
    Dense(1, activation = 'sigmoid', name = 'layers2')
])

In [15]:
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(0.01)
)

In [16]:
model.fit(
    X_train, y_train,
    epochs= 100
)

Epoch 1/100
3/3 [==============================] - 2s 4ms/step - loss: 0.7872
Epoch 2/100
3/3 [==============================] - 0s 7ms/step - loss: 0.6788
Epoch 3/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6312
Epoch 4/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6194
Epoch 5/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6149
Epoch 6/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6044
Epoch 7/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5898
Epoch 8/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5718
Epoch 9/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5530
Epoch 10/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5312
Epoch 11/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5085
Epoch 12/100
3/3 [==============================] - 0s 3ms/step - loss: 0.4855
Epoch 13/100
3/3 [==============================] - 0s 3ms/step - loss: 0.4605
Epoch 14/100
3/3 [==============================] - 0s 3ms/step - loss: 0.4333
Epoch 15/100
3/3 [==============================] - 0s 3ms/step - loss: 0.4049
Epoch 16/100
3/3 [==============================] - 0s 3ms/step - loss: 0.3764
Epoch 17/100
3/3 [==============================] - 0s 3ms/step - loss: 0.3453
Epoch 18/100
3/3 [==============================] - 0s 3ms/step - loss: 0.3167
Epoch 19/100
3/3 [==============================] - 0s 3ms/step - loss: 0.2886
Epoch 20/100
3/3 [==============================] - 0s 3ms/step - loss: 0.2621
Epoch 21/100
3/3 [==============================] - 0s 3ms/step - loss: 0.2330
Epoch 22/100
3/3 [==============================] - 0s 3ms/step - loss: 0.2083
Epoch 23/100
3/3 [==============================] - 0s 3ms/step - loss: 0.1855
Epoch 24/100
3/3 [==============================] - 0s 2ms/step - loss: 0.1649
Epoch 25/100
3/3 [==============================] - 0s 3ms/step - loss: 0.1463
Epoch 26/100
3/3 [==============================] - 0s 2ms/step - loss: 0.1298
Epoch 27/100
3/3 [==============================] - 0s 3ms/step - loss: 0.1156
Epoch 28/100
3/3 [==============================] - 0s 3ms/step - loss: 0.1025
Epoch 29/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0917
Epoch 30/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0821
Epoch 31/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0739
Epoch 32/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0668
Epoch 33/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0606
Epoch 34/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0552
Epoch 35/100
3/3 [==============================] - 0s 2ms/step - loss: 0.0505
Epoch 36/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0464
Epoch 37/100
3/3 [==============================] - 0s 2ms/step - loss: 0.0427
Epoch 38/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0396
Epoch 39/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0368
Epoch 40/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0343
Epoch 41/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0320
Epoch 42/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0301
Epoch 43/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0282
Epoch 44/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0266
Epoch 45/100
3/3 [==============================] - 0s 2ms/step - loss: 0.0251
Epoch 46/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0237
Epoch 47/100
3/3 [==============================] - 0s 5ms/step - loss: 0.0225
Epoch 48/100
3/3 [==============================] - 0s 4ms/step - loss: 0.0214
Epoch 49/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0204
Epoch 50/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0194
Epoch 51/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0186
Epoch 52/100
3/3 [==============================] - 0s 4ms/step - loss: 0.0178
Epoch 53/100
3/3 [==============================] - 0s 4ms/step - loss: 0.0170
Epoch 54/100
3/3 [==============================] - 0s 5ms/step - loss: 0.0163
Epoch 55/100
3/3 [==============================] - 0s 6ms/step - loss: 0.0156
Epoch 56/100
3/3 [==============================] - 0s 6ms/step - loss: 0.0150
Epoch 57/100
3/3 [==============================] - 0s 6ms/step - loss: 0.0145
Epoch 58/100
3/3 [==============================] - 0s 6ms/step - loss: 0.0139
Epoch 59/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0134
Epoch 60/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0129
Epoch 61/100
3/3 [==============================] - 0s 4ms/step - loss: 0.0125
Epoch 62/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0120
Epoch 63/100
3/3 [==============================] - 0s 4ms/step - loss: 0.0117
Epoch 64/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0113
Epoch 65/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0109
Epoch 66/100
3/3 [==============================] - 0s 2ms/step - loss: 0.0106
Epoch 67/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0102
Epoch 68/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0099
Epoch 69/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0096
Epoch 70/100
3/3 [==============================] - 0s 2ms/step - loss: 0.0093
Epoch 71/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0091
Epoch 72/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0088
Epoch 73/100
3/3 [==============================] - 0s 2ms/step - loss: 0.0086
Epoch 74/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0083
Epoch 75/100
3/3 [==============================] - 0s 2ms/step - loss: 0.0081
Epoch 76/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0079
Epoch 77/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0077
Epoch 78/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0075
Epoch 79/100
3/3 [==============================] - 0s 2ms/step - loss: 0.0073
Epoch 80/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0071
Epoch 81/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0069
Epoch 82/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0068
Epoch 83/100
3/3 [==============================] - 0s 2ms/step - loss: 0.0066
Epoch 84/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0065
Epoch 85/100
3/3 [==============================] - 0s 2ms/step - loss: 0.0063
Epoch 86/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0062
Epoch 87/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0060
Epoch 88/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0059
Epoch 89/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0058
Epoch 90/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0056
Epoch 91/100
3/3 [==============================] - 0s 4ms/step - loss: 0.0055
Epoch 92/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0054
Epoch 93/100
3/3 [==============================] - 0s 4ms/step - loss: 0.0053
Epoch 94/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0052
Epoch 95/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0051
Epoch 96/100
3/3 [==============================] - 0s 2ms/step - loss: 0.0050
Epoch 97/100
3/3 [==============================] - 0s 2ms/step - loss: 0.0049
Epoch 98/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0048
Epoch 99/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0047
Epoch 100/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0046

The `model.summary()` provides a description of the network:

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 layer1 (Dense)              (None, 4)                 20

 layers2 (Dense)             (None, 1)                 5

=================================================================
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


4 4 5
O|O|O
O|O|
O|O|
O|O|

LAYERS1
4X4+4 = 20

LAYERS 2
4+1=5
))

The parameter counts shown in the summary correspond to the number of elements in the weight and bias arrays as shown below.

### Performance Analysis

In [22]:
prediction = model.predict(X_test)

1/1 [==============================] - 0s 18ms/step

In [24]:
binaryPred = (prediction > 0.5).astype(int)

for i in range(len(y_test)):
    print(f"Actual: {y_test[i]} - Prediction: {binaryPred[i]}")

Actual: [0] - Prediction: [0]
Actual: [1] - Prediction: [1]
Actual: [0] - Prediction: [0]
Actual: [0] - Prediction: [0]
Actual: [1] - Prediction: [1]
Actual: [1] - Prediction: [1]
Actual: [0] - Prediction: [0]
Actual: [0] - Prediction: [0]
Actual: [1] - Prediction: [1]
Actual: [0] - Prediction: [0]
Actual: [0] - Prediction: [0]
Actual: [1] - Prediction: [1]
Actual: [0] - Prediction: [0]
Actual: [1] - Prediction: [1]
Actual: [0] - Prediction: [0]
Actual: [1] - Prediction: [1]
Actual: [1] - Prediction: [1]
Actual: [0] - Prediction: [0]
Actual: [0] - Prediction: [0]
Actual: [0] - Prediction: [0]

In [26]:
accuracy = tf.keras.metrics.CategoricalAccuracy()(y_test, prediction).numpy()
print(f"Accuracy: {accuracy*100:.2f}%")

Accuracy: 100.00%